[package]
name = "zakura-keys"
description = "Zcash key and address management"
keywords = ["cryptography", "keys", "addresses", "zcash"]
categories = ["cryptography::cryptocurrencies"]
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lib]
name = "zcash_keys"

[dependencies]
bech32 = { version = "0.11", features = ["alloc"], default-features = false }
bip0039 = { version = "0.12", optional = true }
bip32 = { version = "0.6", features = ["alloc"], optional = true, default-features = false }
bs58 = { version = "0.5", features = ["alloc", "check"], default-features = false }
byteorder = { version = "1", optional = true }
corez = { version = "0.1.1", features = ["alloc"], default-features = false }
nonempty = { version = "0.11", default-features = false }
orchard = { workspace = true, optional = true }
proptest = { version = ">=1,<1.7", optional = true }
regex = { version = "1.11", optional = true, default-features = false }
sapling = { workspace = true, optional = true }
secp256k1 = { version = "0.33", features = ["alloc"], optional = true, default-features = false }
secrecy = "0.8"
transparent.workspace = true
zcash_address.workspace = true
zcash_encoding = { version = "0.4", default-features = false }
zcash_protocol.workspace = true
zip32 = { version = "0.2", default-features = false }

[dev-dependencies]
assert_matches = "1.5"
group = "0.14"
hex = { version = "0.4", features = ["alloc"], default-features = false }
orchard = { workspace = true, features = ["circuit"] }
proptest = ">=1,<1.7"
rand = { version = "0.8", default-features = false }
rand_chacha = "0.3"
secp256k1 = { version = "0.33", features = ["alloc"], default-features = false }
subtle = { version = "2.2.3", default-features = false }
transparent = { workspace = true, features = ["test-dependencies"] }
zcash_address = { workspace = true, features = ["test-dependencies"] }
zcash_script = { version = "0.6", default-features = false }

[features]
default = ["std"]
orchard = ["dep:orchard"]
sapling = ["dep:sapling"]
std = [
    "orchard?/std",
    "sapling?/std",
    "transparent/std",
    "zcash_address/std",
]
test-dependencies = [
    "dep:proptest",
    "orchard?/test-dependencies",
    "sapling?/test-dependencies",
    "transparent/test-dependencies",
]
transparent-inputs = ["dep:bip32", "transparent/transparent-inputs"]
transparent-key-encoding = ["dep:bip32", "dep:secp256k1"]
unstable = ["dep:byteorder"]
unstable-frost = ["orchard"]
zcashd-compat = ["dep:bip0039", "dep:regex"]

[lints.rust.unexpected_cfgs]
level = "warn"
priority = 0
check-cfg = [
    "cfg(tokio_unstable)",
    'cfg(zcash_unstable, values("nu7"))',
    "cfg(live_network_tests)",
]
